version: '3'
services:
  app:
    build: .
    container_name: teasy-pos
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/usr/src/app/db.json
    environment:
      - API_KEY=GwabsTeasy123456
    restart: unless-stopped
